version: 1.0.{build}
configuration: Release
platform: x64
install:
- cd sdk/
- 'echo Downloading ScriptHook [Version: 1.0.350.2]'
- appveyor DownloadFile http://dl.johnnycrazy.de/scripthook/ScriptHookV_SDK_1.0.350.2.zip -FileName sdk.zip
- echo Download completed. Extracting...
- 7z x sdk.zip
- echo Extraction complete
- cd ../
build:
  project: ScriptHookVDotNet.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin/Release/
  name: ScriptHookVDotNet
